name: quantactions_flutter_plugin
description: A flutter plugin to add QuantActions functionality to your app
version: 0.1.3
homepage: 'https://quantactions.com'

environment:
  sdk: '>=3.0.3 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  time_machine: ^0.9.17
  get_it: ^7.2.0
  collection: ^1.18.0
  faker: ^2.0.0
  json_annotation: ^4.8.1
  intl: ^0.19.0
  quiver: ^3.2.1
  jiffy: ^6.2.1
  sugar: ^3.1.0
  timezone: ^0.9.2
  dartx: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  plugin:
    platforms:
      android:
        package: com.quantactions.qa_flutter_plugin
        pluginClass: QAFlutterPlugin
      ios:
        pluginClass: QAFlutterPlugin