name: qa_flutter_plugin
description: A cross-platform plugin for QA SDK
version: 0.0.1
homepage: 'https://quantactions.com'

environment:
  sdk: '>=3.0.3 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  time_machine: ^0.9.17
  get_it: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0