name: charts
description: charts features.
publish_to: none

environment:
  sdk: '>=3.1.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  dartx: ^1.1.0
  scidart: ^0.0.2-dev.12
  jiffy: ^6.2.1
  intl: ^0.19.0

  core_ui:
    path: ../core_ui

  quantactions_flutter_plugin: ^0.2.1-rc01

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0